network:
  host: 127.0.0.1
  bootstrapNodes:
    - "/dns4/bootnode-0.testnet.iotex.one/tcp/4689/ipfs/12D3KooWCb1nZdLsR6WBgXqmGnzRvhxASQJaAB3NgwTNk3JE43Wj"
    - "/dns4/a12f5c5ca34a211e9809c02f3dedec74-0c7145ef4e7091ef.elb.us-west-2.amazonaws.com/tcp/4689/ipfs/12D3KooWEgPtefxSeWQHjXFdrze1NicjzqKyVmMgyxqRBRByqi2Q"

chain:
  genesisActionsPath: /etc/iotex/testnet_actions_override.yaml
  chainDBPath: "/var/chain.db"
  trieDBPath: "/var/trie.db"
  beaconChainAPI: "wss://kovan.infura.io/ws"
  beaconChainDB:
    dbPath: "/var/poll.db"
    numRetries: 100
  numCandidates: 24
  enableIndex: true
  enableAsyncIndexWrite: true
  enableSubChainStartInGenesis: false
  # Use your own key, otherwise, every run will use an arbitrary generated key
  # producerPubKey:
  # producerPrivKey:

consensus:
  scheme: "ROLLDPOS"
  rollDPoS:
    fsm:
      unmatchedEventTTL: 3s
      unmatchedEventInterval: 100ms
      acceptBlockTTL: 4s
      acceptProposalEndorsementTTL: 2s
      acceptLockEndorsementTTL: 2s
      eventChanSize: 100000
    delay: 30s

actPool:
  maxNumActsToPick: 2000

system:
  httpProfilingPort: 6060

log:
  zap:
    level: info
    encoding: json
    disableStacktrace: true
    outputPaths: ["stderr", "stdout"]
    errorOutputPaths: ["stderr"]
  stderrRedirectFile: "/data/s.log"
  stdLogRedirect: true

api:
  enabled: true